# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# retrieve client credentials from shaw
---
- name: POSTGRESQL OPERATIONS | checking if {{ encrypted_user }} credentials exist
  stat:
    path: "/etc/tls/datanexus/postgresql/postgresql-{{ encrypted_user }}.key"
  become: true
  register: client_key
  
- block:
  - name: POSTGRESQL OPERATIONS | creating {{ encrypted_user }} SSL private key and csr
    command: /bin/openssl req -nodes -newkey rsa:2048 -keyout "/etc/tls/datanexus/postgresql/postgresql-{{ encrypted_user }}.key" -out /etc/tls/datanexus/postgresql/postgresql-client.csr -subj "/C=US/ST=CO/L=Denver/O=DataNexus/CN={{ encrypted_user }}"      
    
  - name: POSTGRESQL OPERATIONS | signing {{ encrypted_user }} private key and writing certificate
    command: /bin/openssl x509 -req -in /etc/tls/datanexus/postgresql/postgresql-client.csr -CA /etc/tls/datanexus/ca/ca-cert.pem -CAkey /etc/tls/datanexus/ca/ca-key.pem -out /etc/tls/datanexus/postgresql/postgresql-{{ encrypted_user }}.crt -CAcreateserial

  - name: POSTGRESQL OPERATIONS | setting client key permissions
    file:
      path: "/etc/tls/datanexus/postgresql/postgresql-{{ encrypted_user }}.key"
      owner: root
      group: root
      mode: 0600

  - name: POSTGRESQL OPERATIONS | removing csr
    file:
      path: /etc/tls/datanexus/postgresql/postgresql-client.csr
      state: absent

  become: true      
  when: not client_key.stat.exists
