# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# deploy any tenant workers
--- 
- block:
  
  - name: OPERATIONS OVERLAY (INSTALL CONNECTORS) | checking existing connectors on http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors
    uri:
      url: "http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors"
      method: GET
      status_code: 200
    register: active_connectors
    when:
      - groups['connect_public'] | length > 0
  
  - name: OPERATIONS OVERLAY (INSTALL CONNECTORS) | stopping http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors/replicator
    uri:
      url: "http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors/replicator"
      method: DELETE
      status_code: 204
      body_format: json
    when:
      - groups['connect_public'] | length > 0
      - '"replicator" in active_connectors.json'
      
  # only POST a new connector if the name is unique
  - name: OPERATIONS OVERLAY (INSTALL CONNECTORS) | creating connectors on http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors
    uri:
      url: "http://{{ groups['connect_public'] | first }}:{{ connect.distributed.config.restPort }}/connectors"
      method: POST
      body: "{{ item }}"
      status_code: 201
      body_format: json
    loop: "{{ connectors }}"
    loop_control:
      loop_var: item
    when:
      - groups['connect_public'] | length > 0
      - not item.name in active_connectors.json
  
  when:
    - connectors is defined
