# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# retrieve subject credentials from shaw
---
- block:  
  - name: POSTGRESQL OPERATIONS | fetching {{ subject }} credentials to {{ key_path }}
    fetch:
      src: "{{ src_path }}/{{ item }}"
      dest: "{{ dst_path }}/{{ item }}"
      flat: yes
  
  - name: POSTGRESQL OPERATIONS | fetching root certificate to {{ key_path }}
    fetch:
      src: "/etc/tls/datanexus/ca/ca-cert.pem"
      dest: "{{ dst_path}}/ca-cert.pem"
      flat: yes
    when: subject != 'CA'
  become: true