# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# this duplicates a lot of the variables in the kafka platform defaults
# while annoying to keep in sync, this is so operations can be a true separate overlay
apache:
  packages:
    epel_version: '7-11'
    java_version: '1.8.0'
    kafka_version: '2.3.1'
    scala_version: '2.12'
  install_dir: /usr/local
confluent:
  packages:
    epel_version: '7-11'
    java_version: '1.8.0'
    confluent_version: '5.3'
    minor_release: '0'
    scala_version: '2.12'
    # kafka_version isn't used under confluent, here mainly to match apache
    kafka_version: '2.3.1'
shaw:
  config:
    tls_path: "{{ (got_root | default('yes')) | ternary('/etc/tls', (datanexus_root + '/datanexus/tls')) }}"
broker:
  apache:
    user: kafka
    group: kafka
    service_name: apache-kafka
    config_file: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/config/server.properties"
  confluent:
    user: "{{ (got_root | default('yes')) | ternary('cp-kafka', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    service_name: confluent-kafka
    config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka/server.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka/server.properties')) }}"
  application: kafka_broker
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
  config:
    port: '9092'
    sslPort: '9091'
zookeeper:
  apache:
    user: kafka
    group: kafka
    service_name: apache-zookeeper
  confluent:
    user: "{{ (got_root | default('yes')) | ternary('cp-kafka', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    service_name: confluent-zookeeper
  application: zookeeper
  config:
    port: '2181'
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
connect:
  distributed:
    apache:
      config_file: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/config/connect-distributed.properties"
      user: kafka
      group: kafka
      service_name: apache-kafka-connect
    confluent:
      config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka/connect-distributed.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka/connect-distributed.properties')) }}"
      user: "{{ (got_root | default('yes')) | ternary('cp-kafka-connect', ansible_user) }}"
      group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
      service_name: confluent-kafka-connect
    user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
schema:
  registry:
    user: "{{ (got_root | default('yes')) | ternary('cp-schema-registry', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    config_file: "{{ (got_root | default('yes')) | ternary('/etc/schema-registry/schema-registry.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/schema-registry/schema-registry.properties')) }}"
    service_name: confluent-schema-registry
    user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
    config:
      listener_port: '8081'
control:
  center:
    user: "{{ (got_root | default('yes')) | ternary('cp-control-center', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    config_file: "{{ (got_root | default('yes')) | ternary('/etc/confluent-control-center/control-center-production.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/confluent-control-center/control-center-production.properties')) }}"
    service_name: confluent-control-center
    user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
cruisecontrol:
  config_file: /usr/local/src/cruise-control/config/cruisecontrol.properties
  user: "{{ (apache_kafka) | ternary('kafka', 'cp-kafka') }}"
  group: "{{ (apache_kafka) | ternary('kafka', 'confluent') }}"
  service_name: cruise-control
  user_service: /usr/local/bin
ksql:
  config_file: "{{ (got_root | default('yes')) | ternary('/etc/ksql/ksql-server.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/ksql/ksql-server.properties')) }}"
  service_name: confluent-ksql
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
  user: "{{ (got_root | default('yes')) | ternary('cp-ksql', ansible_user) }}"
  group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
kafkarest:
  user: "{{ (got_root | default('yes')) | ternary('cp-kafka-rest', ansible_user) }}"
  group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
  config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka-rest/kafka-rest.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka-rest/kafka-rest.properties')) }}"
  service_name: confluent-kafka-rest
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
  config:
    rest_port: '8082'
telegraf:
  enabled: "{{ telegraf_enabled | default('yes') }}"
  service_name: telegraf
  user: "{{ (got_root | default('yes')) | ternary('telegraf', ansible_user) }}"
  group: "{{ (got_root | default('yes')) | ternary('telegraf', ansible_user) }}"
