# postflight variables
postflight:
  utilsDir: /usr/local/bin
zookeeper:
  config:
    # this needs to be quoted as a string for concatenation purposes
    # if this gets changed it all needs to be changed under kafka defaults
    port: '2181'
broker:
  application: kafka_broker
  user: cp-kafka
  group: confluent
  config:
    # this needs to be quoted as a string for concatenation purposes
    # if this gets changed it needs to be changed under connect defaults
    port: '9092'
    sslPort: '9091'