# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during telegraf installation
---  
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart telegraf
  systemd:
    name: "{{ telegraf.service_name }}" 
    state: restarted
  become: true