# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# tasks that occur post-appplication installation
---
# install helper utilities
- import_tasks: utilities.yml

- block:
  
  - name: ENCRYPTION OVERLAY (POSTFLIGHT) | checking existing server keystore
    stat:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
    register: kafka_server_key
  
  - name: ENCRYPTION OVERLAY (POSTFLIGHT) | ensure TLS kafka directory is present
    file:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
      state: directory
      mode: 0755
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    when: not kafka_server_key.stat.exists
  
  - name: ENCRYPTION OVERLAY (POSTFLIGHT) | checking existing {{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/client-ssl.properties
    stat:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/client-ssl.properties"
    register: existing_ssl_config
    
  - name: ENCRYPTION OVERLAY (POSTFLIGHT) | updating client ssl properties
    template:
      src: client-ssl.properties.j2
      dest: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/client-ssl.properties"
      mode: 0644
      owner: "{{ ansible_user }}"
      group:  "{{ ansible_user }}"
    when:
      - not existing_ssl_config.stat.exists
      
  become: "{{ got_root | default('yes') }}"
