# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# install/update kafka cluster helper utilities
---
- set_fact:
    apache_bin: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/bin"
    
- set_fact:
    dn_bin_path: "{{ (got_root | default('yes')) | ternary('/usr/bin', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/bin')) }}"

- set_fact:
    utils_path: "{{ (apache_kafka) | ternary(apache_bin, dn_bin_path) }}"

- block:

  - name: ENCRYPTION OVERLAY (POSTFLIGHT) | installing updated kafka topic consume utility for encrypted brokers
    template:
      src: consume-topic.j2
      dest: "{{ postflight.utilsDir }}/consume-topic"
      mode: 0755
      owner: "{{ broker.user }}"
      group: "{{ broker.group }}"
    when:
      - groups['kafka_broker'] is defined
      - groups['kafka_broker'] | length > 0
      
  become: "{{ got_root | default('yes') }}"
