# configuration variables for kafka distributed connector services
connect:
  distributed:
    config_file: /etc/kafka/connect-distributed.properties
    service_name: confluent-kafka-connect
    systemd_override: /etc/systemd/system/confluent-kafka-connect.service.d
    user_service: /usr/local/bin
    user: cp-kafka-connect
    group: confluent
    config:
      restPort: 8083
    # tune the key converter to the message
    # kafka-console-consumer --bootstrap-server X:9092 --property print.key=true --from-beginning --topic X
    connectors:
      - name: es_log_sink
        config:
          connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
          tasks.max: 1
          topics: telegraf_log
          topic.index.map: telegraf_log:log_index
          connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
          type.name: true
          key.ignore: true
          schema.ignore: true
          schemas.enable: false
          key.converter: org.apache.kafka.connect.storage.StringConverter
      # - name: es_cpu_sink
#         config:
#           connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#           tasks.max: 1
#           topics: telegraf_cpu
#           topic.index.map: telegraf_cpu:cpu_index
#           connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
#           type.name: true
#           key.ignore: true
#           schema.ignore: true
#           schemas.enable: false
#           key.converter: org.apache.kafka.connect.storage.StringConverter
#       - name: es_disk_sink
#         config:
#           connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#           tasks.max: 1
#           topics: telegraf_disk
#           topic.index.map: telegraf_disk:disk_index
#           connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
#           type.name: true
#           key.ignore: true
#           schema.ignore: true
#           schemas.enable: false
#           key.converter: org.apache.kafka.connect.storage.StringConverter
      - name: es_diskio_sink
        config:
          connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
          tasks.max: 1
          topics: telegraf_diskio
          topic.index.map: telegraf_diskio:diskio_index
          connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
          type.name: true
          key.ignore: true
          schema.ignore: true
          schemas.enable: false
          key.converter: org.apache.kafka.connect.storage.StringConverter
#       - name: es_kernel_sink
#         config:
#           connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#           tasks.max: 1
#           topics: telegraf_kernel
#           topic.index.map: telegraf_kernel:kernel_index
#           connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
#           type.name: true
#           key.ignore: true
#           schema.ignore: true
#           schemas.enable: false
#           key.converter: org.apache.kafka.connect.storage.StringConverter
      - name: es_mem_sink
        config:
          connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
          tasks.max: 1
          topics: telegraf_mem
          topic.index.map: telegraf_mem:mem_index
          connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
          type.name: true
          key.ignore: true
          schema.ignore: true
          schemas.enable: false
          key.converter: org.apache.kafka.connect.storage.StringConverter
      - name: es_processes_sink
        config:
          connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
          tasks.max: 1
          topics: telegraf_processes
          topic.index.map: telegraf_processes:processes_index
          connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
          type.name: true
          key.ignore: true
          schema.ignore: true
          schemas.enable: false
          key.converter: org.apache.kafka.connect.storage.StringConverter
#       - name: es_swap_sink
#         config:
#           connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#           tasks.max: 1
#           topics: telegraf_swap
#           topic.index.map: telegraf_swap:swap_index
#           connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
#           type.name: true
#           key.ignore: true
#           schema.ignore: true
#           schemas.enable: false
#           key.converter: org.apache.kafka.connect.storage.StringConverter
#       - name: es_system_sink
#         config:
#           connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#           tasks.max: 1
#           topics: telegraf_system
#           topic.index.map: telegraf_system:system_index
#           connection.url: "http://{{ groups['elasticsearch_public'] | first }}:{{ elasticsearch.config.restPort }}"
#           type.name: true
#           key.ignore: true
#           schema.ignore: true
#           schemas.enable: false
#           key.converter: org.apache.kafka.connect.storage.StringConverter
broker:
   config:
     # if this gets changed it needs to be changed under kafka defaults
     broker_port: '9092'
elasticsearch:
  config:
    # this needs to be quoted as a string for concatenation purposes
    # if this gets changed it needs to be changed under connect defaults
    restPort: '9200'