# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# broker client
---
- block:  
  
  - name: ENCRYPTION OVERLAY (CLIENT) | checking existing server keystore
    stat:
      path: "/etc/tls/{{ tenant }}/{{ broker.application }}"
    register: kafka_server_key
  
  - name: ENCRYPTION OVERLAY (CLIENT) | ensure TLS kafka directory is present
    file:
      path: /etc/tls/{{ tenant }}/{{ broker.application }}
      state: directory
      mode: 0755
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    when: not kafka_server_key.stat.exists
  
  - name: ENCRYPTION OVERLAY (CLIENT) | copying client ssl properties
    template:
      src: ../../postflight/templates/client-ssl.properties.j2
      dest: "/etc/tls/{{ tenant }}/{{ broker.application }}/client-ssl.properties"
      mode: 0644
      owner: "{{ ansible_user }}"
      group:  "{{ ansible_user }}"
      
  # we set the perms to 644 in case we're overwriting an existing service
  - name: ENCRYPTION OVERLAY (CLIENT) | copying broker client stores
    copy:
      src: "{{ key_path }}/{{ item }}"
      dest: "/etc/tls/{{ tenant }}/{{ broker.application }}/{{ item }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
    with_items:
      - kafka.client.keystore.jks
      - kafka.client.truststore.jks
  
  become: true 
