# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# enable broker encryption
---
- block:
  
  - name: ENCRYPTION OVERLAY (CONTROL CENTER) | checking existing server keystore
    stat:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
    register: kafka_server_key
  
  - name: ENCRYPTION OVERLAY (CONTROL CENTER) | ensure TLS {{ broker.application }} directory is present
    file:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
      state: directory
      mode: 0755
      owner: "{{ control.center.user }}"
      group: "{{ control.center.group }}"
    when: not kafka_server_key.stat.exists

  - name: ENCRYPTION OVERLAY (CONTROL CENTER) | distributing certificates to control center node(s)
    copy:
      src: "{{ item }}"
      dest: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/"
      owner: "{{ control.center.user }}"
      group: "{{ control.center.group }}"
      mode: 0600
    with_items:
      - "{{ key_path }}/kafka.client.keystore.jks"
      - "{{ key_path }}/kafka.client.truststore.jks"
    notify: restart controlcenter
  
  - name: ENCRYPTION OVERLAY (CONTROL CENTER) | configuring bootstrap servers
    lineinfile:
      path: "{{ control.center.config_file }}"
      regexp: '^bootstrap.servers='
      line: "bootstrap.servers={{ groups['kafka_public'][:5] | join(':' + broker.config.sslPort + ',') }}:{{ broker.config.sslPort }}"
      insertafter: '^#bootstrap.servers='
    notify: restart controlcenter
      
  - name: ENCRYPTION OVERLAY (CONTROL CENTER) | enabling SSL for internode communication
    blockinfile:
      path: "{{ control.center.config_file }}"
      insertafter: EOF
      state: present
      block: |
        confluent.controlcenter.streams.security.protocol=SSL
        confluent.controlcenter.streams.ssl.truststore.location={{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/kafka.client.truststore.jks
        confluent.controlcenter.streams.ssl.truststore.password={{ storepass }}
        confluent.controlcenter.streams.ssl.keystore.location={{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/kafka.client.keystore.jks
        confluent.controlcenter.streams.ssl.keystore.password={{ storepass }}
        confluent.controlcenter.streams.ssl.key.password={{ keypass }}
    notify: restart controlcenter
  
  become: "{{ got_root | default('yes') }}"
