# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# enable schema registry encryption
---
- block:
  
  - name: ENCRYPTION OVERLAY (SCHEMA REGISTRY) | checking existing server keystore
    stat:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
    register: kafka_server_key
  
  - name: ENCRYPTION OVERLAY (SCHEMA REGISTRY) | ensure TLS {{ broker.application }} directory is present
    file:
      path: "{{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}"
      state: directory
      mode: 0755
      owner: "{{ schema.registry.user }}"
      group: "{{ schema.registry.group }}"
    when: not kafka_server_key.stat.exists

  - import_tasks: generate-client.yml
    vars:
      client_name: 'SCHEMA REGISTRY'
      client_owner: "{{ schema.registry.user }}"
      client_group: "{{ schema.registry.group }}"
      client_handler: registry
  
  - name: ENCRYPTION OVERLAY (SCHEMA REGISTRY) | disabling zookeeper connections
    lineinfile:
      path: "{{ schema.registry.config_file }}"
      regexp: "^kafkastore.connection.url={{ groups['zookeeper'] | join(':' + zookeeper.config.port + ',') }}:{{ zookeeper.config.port }}"
      line: "#kafkastore.connection.url={{ groups['zookeeper'] | join(':' + zookeeper.config.port + ',') }}:{{ zookeeper.config.port }}"
    notify: restart registry
    
  - name: ENCRYPTION OVERLAY (SCHEMA REGISTRY) | configuring bootstrap servers
    lineinfile:
      path: "{{ schema.registry.config_file }}"
      regexp: '^kafkastore.bootstrap.servers='
      line: "kafkastore.bootstrap.servers=SSL://{{ groups['kafka_public'][:5] | join(':' + broker.config.sslPort + ',SSL://') }}:{{ broker.config.sslPort }}"
      insertafter: '^#kafkastore.bootstrap.servers='
    notify: restart registry
      
  - name: ENCRYPTION OVERLAY (SCHEMA REGISTRY) | enabling SSL for broker communication
    blockinfile:
      path: "{{ schema.registry.config_file }}"
      insertafter: EOF
      state: present
      block: |
        kafkastore.security.protocol=SSL
        kafkastore.ssl.truststore.location={{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/kafka.client.truststore.jks
        kafkastore.ssl.truststore.password={{ cert.storepass }}
        kafkastore.ssl.keystore.location={{ shaw.config.tls_path }}/{{ tenant }}/{{ broker.application }}/kafka.client.keystore.jks
        kafkastore.ssl.keystore.password={{ cert.storepass }}
        kafkastore.ssl.key.password={{ cert.keypass }}
    notify: restart registry
  
  become: "{{ got_root | default('yes') }}"
