#!/usr/bin/env sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
# telegraf deployment wrapper

: "${AWS_PROFILE:=datanexus}" && export AWS_PROFILE="$AWS_PROFILE"    # sets this to a reasonable ~/.aws/credentials default

if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
    printf "Usage:   deploy [-h]\\thelp\\n"
    printf "\\t deploy [FILE | TENANT PROJECT CLOUD REGION DOMAIN CLUSTER SSH_USER KAFKA_USER TENANT_PATH KEY_PATH APPLICATION_PATH]\\tdeploy %s overlay with FILE configuration or with the specified values\\n" "$application"
    printf "Example: deploy encryption datanexus demo aws us-east-1 development a centos kafka /tmp/datanexus /tmp /tmp/postgresql\\n"
    printf "\\t deploy /tmp/configuration.yml\\n"
    exit 0
fi

export application="$1"   #  overlay to deploy

# if encryption is deployed statically; grab the inventory from the front and dump the argument
if [ $# -eq 9 ]  && [ -d "${9}" ]; then
  INVENTORY="--inventory=${2}"
  cluster=`basename ${2} | cut -d. -f2`       # derive the cluster if not passed in
  shift && shift
else
  cluster=${7}
fi

tenant=`/usr/bin/basename ${6}`         # derive tenant name from the path

# likely called by the orchestrator to just pass through everything
if [ $# -eq 3 ] && [ "$2" = "-e" ]; then
  ./overlay-"$application" "$2" "$3"

# deploy telegraf as an overlay without the orchestrator
elif [ $# -eq 7 ] && [ -d "${7}" ]; then
  ./overlay-"$application" $INVENTORY -e "project=$1 cloud=$2 region=$3 domain=$4 user=${5} tenant_config_path=${6} key_path=${7} tenant=${tenant} cluster=${cluster}"
# elif [ $# -eq 1 ] && [ -f "$1" ] && [ -s "$1" ]; then
#   ./provision-postgresql --tags "vm,$application" -e "configuration=$1"
fi
